language: python
python:
- 3.6
- 3.7
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: archatas
  password:
    secure: Gg4BiCKTyrORKGa1Y29Mvw07zjWDtP2ZuRz/IUJwWGuFGYUWDaiaOWe8ixtVMV40LbNeWsUvrWWO6nzMNZH9rnFGimCHkPLrC9nREV4Q7prxD37g9PW+6NpZn3W9LDsIs35bpw7qfeLOcaJESHJbxvMrNyY1UXPufIsgBTgBcGJyAPZCdowv3zE/YCCewmuxgScPI2IebJ9+0fsHd8XNhDPhWMbzdVXxs9xfEGrzJne8SmnNkUpVBlxmj0hm0VKfN5XtVOmXxo5OSUNHBzsPnSSPGhllQK4F+QvnU+qXuyS5HQ1cuGvVpocu3CGObT/Hte/mhuKtngQBIgD8ZLMbAtduXLNzyWlkETLEVH+4A6KWZP2oH9kiEOB5ClQhtqJHUl/Q9bHmlXoKS0FUl2zPKR1gn0sShuVXhgVA5GhKcl3aj77mCMT7kwzmlC779cwiyrwxue4lgKh7kjtuy28VsZ+9GEKqwh6DavKyr9jPsah53oNLCmN3fcVOEvKzzapTAyzOktBJqC5j21x/Q/pK7gKbYEuKucb0HQgUYrcrsRj6GLJIcwz4hwStyRkpWGtUVvP0bjOr1LgZ/4a6j/ydm3l5TqSvoMpe8/bdkYfD2sA3b/GhEJdazXfXpE7kQC8h3uEAhwQSMOBgE7Yn1TAFbIzILOxafKtbywVsvLMg0XU=
  on:
    tags: true
    repo: archatas/search_in_api
    python: 3.6
